[mgr]
prepend_keymap = [
	{ on = [ "A" ],   			run = "toggle_all --state=on",            																									desc = "Select all files" },
	{ on = [ "R" ],   			run = "toggle_all",            																												desc = "Inverse selection of all files" },
	{ on = [ "!" ], 			run = 'shell "$SHELL" --block', 			   																								desc = "Open shell here" },
	{ on = [ "<Up>"],			run = "plugin arrow -1",																													desc = "Add circular navigation feature (up arrow key)" },
	{ on = [ "<Down>"],			run = "plugin arrow 1",											    																		desc = "Add circular navigation feature (down arrow key)" },
	{ on = [ "<Enter>" ],   	run = "plugin smart-enter",                       																							desc = "Smart enter: enter for directory, open for file" },
	{ on = [ "T" ],				run = "plugin toggle-pane max-preview",																										desc = "Maximize preview pane" },
	{ on = ["M"],				run = "plugin mount",																														desc = "Show mount options" },
	{ on = [ "g", "d" ],        run = "cd ~/Downloads",    	   																												desc = "Go to Downloads directory" },
	{ on = [ "g", "u" ],        run = "cd /run/media",    	   																												desc = "Go to the usb mount directory" },
	{ on = [ "g", "a" ],        run = "cd /run/user/1000/gvfs",    	   																										desc = "Go to the mtp mount directory" },
	{ on = [ "g", "n" ],        run = "cd /mnt/nfs",    	   																												desc = "Go to the nfs directory" },
	{ on = [ "g", "s" ],        run = "cd /mnt/sshfs/",    	   																												desc = "Go to the sshfs directory" },
	{ on = [ "g", "`" ],        run = "cd /",    	   																														desc = "Go to the root directory" },
	{ on = [ "'", "r" ], 		run = ['shell "rsync -auvP --info=progress2 \"$@\" \"$PWD\"" --block', 'escape'],															desc = "Copy with rsync" },
	{ on = [ "'", "w" ], 		run = 'shell "swww img --transition-type grow \"$@\""', 																					desc = "Change wallpaper with swww" },
	{ on = [ "'", "x" ], 		run = 'shell "7z x \"$@\"" --block',																										desc = "Extract password-protected archives" },
	{ on = [ "'", "z" ], 		run = 'shell "read -p \"Archive name: \" an && zip -r \"${an}.zip\" $(realpath --relative-to=\"$(pwd)\" \"$@\")" --block',					desc = "Zip selected items" },
	{ on = [ "'", "s" ], 		run = ['shell "tailscale file cp \"$@\" phone:" --block', 'escape'],																		desc = "Send to phone via tailscale" },
	{ on = [ "'", "S" ], 		run = ['shell "tailscale file cp \"$@\" tablet:" --block', 'escape'],																		desc = "Send to tablet via tailscale" },
	{ on = [ "'", "t" ], 		run = ['shell "tailscale file cp \"$@\" thinkpad:" --block', 'escape'],																		desc = "Send to thinkpad via tailscale" },
	{ on = [ "'", "T" ], 		run = ['shell "tailscale file cp \"$@\" ideapad:" --block', 'escape'],																		desc = "Send to ideapad via tailscale" },
]
